### ISSUE TITLE
休眠问题

### ISSUE THREAD

**Issue by itog-blue** [nsinm/13400F-B760M-EFI#8]
你好  配置和你一样  没装 wifi蓝牙
短期内  手动休眠和唤醒都可以
但是晚上睡前休眠 睡一半电脑突然启动 风扇和灯都回亮  你们有这个问题吗？
这个问题真的很头疼~~~

**Comment by nsinm** [comment]
系统电源管理计划任务的问题，关闭电源计划任务后，还会出现，这个还没办法解决
